input_seqs: data/fastas/gfp_lib_450-550.fasta
primers: data/test_primers.csv

output_dir: output/gfp_genes

enzyme: BsaI
upstream_bbsite: AATG
downstream_bbsite: TTAG
other_used_sites: null
ligation_data: T4_18h_37C

njunctions: 50
nopt_steps: 1000
nopt_runs: 5
njobs: 5
oligo_len: 300

add_primers: true
pad_oligos: true

dev: false  # remove
min_size: 40  # remove
other_enzymes: null
opt_seeds: null
optimization: simulated_annealing
